{% set name = "tile_mate" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tile-mate-{{ version }}.tar.gz
  sha256: 2461982122dfec60e0a90dfa4524fa1113482cd7700ef5fb0bfaaf84fb4897cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - python-build
    - setuptools >=60
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=3.9
    - boto3
    - rasterio
    - tqdm
    - geopandas
    - importlib_metadata
    - matplotlib-base
    - numpy
    - pandas
    - pandera
    - shapely
    - dem_stitcher >=2.5.4

test:
  imports:
    - tile_mate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OPERA-Cal-Val/tile-mate
  summary: Create rasters from global tiles
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - cmarshak
    - jhkennedy
