{% set name = "tile_mate" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e8fbec1d21ab966b1a09efd2490a622067e48b0f28d47d7570c173b65c667648

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - python-build
    - setuptools >=60
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=3.9
    - boto3
    - rasterio
    - tqdm
    - geopandas
    - importlib_metadata
    - matplotlib-base
    - numpy <2.0
    - pandas
    - pandera
    - shapely
    - dem_stitcher >=2.5.4

test:
  imports:
    - tile_mate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OPERA-Cal-Val/tile-mate
  summary: Create rasters from global tiles
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - cmarshak
    - jhkennedy
